export interface Player {
  id: string;
  name: string;
  nameAr: string;
  team: string;
  teamLogo: string;
  nationality: string;
  position: string;
  number: number;
  goals: number;
  assists: number;
  rating: number;
  matches: number;
  image: string;
  trending: boolean;
}

export interface Tournament {
  id: string;
  name: string;
  nameFr: string;
  nameAr: string;
  country: string;
  continent: string;
  status: "ongoing" | "upcoming" | "completed";
  stage: string;
  stageFr: string;
  stageAr: string;
  startDate: string;
  endDate: string;
  teams: number;
  logo: string;
}

export interface Match {
  id: string;
  tournament: string;
  homeTeam: string;
  awayTeam: string;
  homeScore: number;
  awayScore: number;
  status: "live" | "ft" | "ht" | "upcoming";
  minute?: number;
  date: string;
  homeLogo: string;
  awayLogo: string;
}

export const players: Player[] = [
  {
    id: "1",
    name: "Kylian Mbappé",
    nameAr: "كيليان مبابي",
    team: "Real Madrid",
    teamLogo: "⚪",
    nationality: "🇫🇷",
    position: "Forward",
    number: 7,
    goals: 28,
    assists: 11,
    rating: 8.9,
    matches: 34,
    image: "/players/mbappe.jpg",
    trending: true,
  },
  {
    id: "2",
    name: "Erling Haaland",
    nameAr: "إيرلينغ هالاند",
    team: "Manchester City",
    teamLogo: "🔵",
    nationality: "🇳🇴",
    position: "Forward",
    number: 9,
    goals: 32,
    assists: 5,
    rating: 8.7,
    matches: 33,
    image: "/players/haaland.jpg",
    trending: true,
  },
  {
    id: "3",
    name: "Jude Bellingham",
    nameAr: "جود بيلينغهام",
    team: "Real Madrid",
    teamLogo: "⚪",
    nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    position: "Midfielder",
    number: 5,
    goals: 18,
    assists: 12,
    rating: 8.6,
    matches: 35,
    image: "/players/bellingham.jpg",
    trending: true,
  },
  {
    id: "4",
    name: "Vinícius Júnior",
    nameAr: "فينيسيوس جونيور",
    team: "Real Madrid",
    teamLogo: "⚪",
    nationality: "🇧🇷",
    position: "Forward",
    number: 7,
    goals: 22,
    assists: 14,
    rating: 8.5,
    matches: 36,
    image: "/players/vinicius.jpg",
    trending: true,
  },
  {
    id: "5",
    name: "Mohamed Salah",
    nameAr: "محمد صلاح",
    team: "Liverpool",
    teamLogo: "🔴",
    nationality: "🇪🇬",
    position: "Forward",
    number: 11,
    goals: 24,
    assists: 13,
    rating: 8.4,
    matches: 34,
    image: "/players/salah.jpg",
    trending: true,
  },
  {
    id: "6",
    name: "Lamine Yamal",
    nameAr: "لامين يامال",
    team: "FC Barcelona",
    teamLogo: "🔵🔴",
    nationality: "🇪🇸",
    position: "Forward",
    number: 19,
    goals: 12,
    assists: 16,
    rating: 8.3,
    matches: 32,
    image: "/players/yamal.jpg",
    trending: true,
  },
];

export const tournaments: Tournament[] = [
  {
    id: "1",
    name: "UEFA Champions League",
    nameFr: "Ligue des Champions UEFA",
    nameAr: "دوري أبطال أوروبا",
    country: "Europe",
    continent: "Europe",
    status: "ongoing",
    stage: "Quarter-Finals",
    stageFr: "Quarts de Finale",
    stageAr: "ربع النهائي",
    startDate: "2025-09-17",
    endDate: "2026-05-30",
    teams: 36,
    logo: "🏆",
  },
  {
    id: "2",
    name: "English Premier League",
    nameFr: "Premier League Anglaise",
    nameAr: "الدوري الإنجليزي الممتاز",
    country: "England",
    continent: "Europe",
    status: "ongoing",
    stage: "Matchday 30",
    stageFr: "Journée 30",
    stageAr: "الجولة 30",
    startDate: "2025-08-16",
    endDate: "2026-05-24",
    teams: 20,
    logo: "🦁",
  },
  {
    id: "3",
    name: "La Liga",
    nameFr: "La Liga",
    nameAr: "الدوري الإسباني",
    country: "Spain",
    continent: "Europe",
    status: "ongoing",
    stage: "Matchday 28",
    stageFr: "Journée 28",
    stageAr: "الجولة 28",
    startDate: "2025-08-15",
    endDate: "2026-05-24",
    teams: 20,
    logo: "⭐",
  },
  {
    id: "4",
    name: "Serie A",
    nameFr: "Serie A",
    nameAr: "الدوري الإيطالي",
    country: "Italy",
    continent: "Europe",
    status: "ongoing",
    stage: "Matchday 29",
    stageFr: "Journée 29",
    stageAr: "الجولة 29",
    startDate: "2025-08-17",
    endDate: "2026-05-25",
    teams: 20,
    logo: "🇮🇹",
  },
  {
    id: "5",
    name: "Bundesliga",
    nameFr: "Bundesliga",
    nameAr: "الدوري الألماني",
    country: "Germany",
    continent: "Europe",
    status: "ongoing",
    stage: "Matchday 27",
    stageFr: "Journée 27",
    stageAr: "الجولة 27",
    startDate: "2025-08-23",
    endDate: "2026-05-17",
    teams: 18,
    logo: "🇩🇪",
  },
  {
    id: "6",
    name: "Ligue 1",
    nameFr: "Ligue 1",
    nameAr: "الدوري الفرنسي",
    country: "France",
    continent: "Europe",
    status: "ongoing",
    stage: "Matchday 28",
    stageFr: "Journée 28",
    stageAr: "الجولة 28",
    startDate: "2025-08-16",
    endDate: "2026-05-17",
    teams: 18,
    logo: "🇫🇷",
  },
  {
    id: "7",
    name: "FIFA Club World Cup 2025",
    nameFr: "Coupe du Monde des Clubs FIFA 2025",
    nameAr: "كأس العالم للأندية 2025",
    country: "USA",
    continent: "World",
    status: "upcoming",
    stage: "Group Stage",
    stageFr: "Phase de Groupes",
    stageAr: "دور المجموعات",
    startDate: "2025-06-15",
    endDate: "2025-07-13",
    teams: 32,
    logo: "🌍",
  },
  {
    id: "8",
    name: "CAF Champions League",
    nameFr: "Ligue des Champions CAF",
    nameAr: "دوري أبطال أفريقيا",
    country: "Africa",
    continent: "Africa",
    status: "ongoing",
    stage: "Semi-Finals",
    stageFr: "Demi-Finales",
    stageAr: "نصف النهائي",
    startDate: "2025-08-16",
    endDate: "2026-05-24",
    teams: 16,
    logo: "🌍",
  },
  {
    id: "9",
    name: "Copa Libertadores",
    nameFr: "Copa Libertadores",
    nameAr: "كوبا ليبرتادوريس",
    country: "South America",
    continent: "South America",
    status: "ongoing",
    stage: "Group Stage",
    stageFr: "Phase de Groupes",
    stageAr: "دور المجموعات",
    startDate: "2026-02-05",
    endDate: "2026-11-29",
    teams: 47,
    logo: "🏆",
  },
  {
    id: "10",
    name: "Saudi Pro League",
    nameFr: "Saudi Pro League",
    nameAr: "دوري روشن السعودي",
    country: "Saudi Arabia",
    continent: "Asia",
    status: "ongoing",
    stage: "Matchday 24",
    stageFr: "Journée 24",
    stageAr: "الجولة 24",
    startDate: "2025-08-21",
    endDate: "2026-05-30",
    teams: 18,
    logo: "🇸🇦",
  },
  {
    id: "11",
    name: "Botola Pro",
    nameFr: "Botola Pro",
    nameAr: "البطولة الاحترافية المغربية",
    country: "Morocco",
    continent: "Africa",
    status: "ongoing",
    stage: "Matchday 22",
    stageFr: "Journée 22",
    stageAr: "الجولة 22",
    startDate: "2025-08-23",
    endDate: "2026-06-07",
    teams: 16,
    logo: "🇲🇦",
  },
  {
    id: "12",
    name: "AFC Champions League Elite",
    nameFr: "Ligue des Champions AFC Elite",
    nameAr: "دوري أبطال آسيا النخبة",
    country: "Asia",
    continent: "Asia",
    status: "ongoing",
    stage: "Round of 16",
    stageFr: "Huitièmes de Finale",
    stageAr: "دور الـ16",
    startDate: "2025-09-16",
    endDate: "2026-05-04",
    teams: 24,
    logo: "🌏",
  },
];

export const matches: Match[] = [
  {
    id: "1",
    tournament: "UEFA Champions League",
    homeTeam: "Real Madrid",
    awayTeam: "Arsenal",
    homeScore: 2,
    awayScore: 1,
    status: "live",
    minute: 67,
    date: "2026-03-17",
    homeLogo: "⚪",
    awayLogo: "🔴",
  },
  {
    id: "2",
    tournament: "UEFA Champions League",
    homeTeam: "Bayern Munich",
    awayTeam: "Inter Milan",
    homeScore: 1,
    awayScore: 1,
    status: "ht",
    minute: 45,
    date: "2026-03-17",
    homeLogo: "🔴",
    awayLogo: "🔵⚫",
  },
  {
    id: "3",
    tournament: "Premier League",
    homeTeam: "Liverpool",
    awayTeam: "Manchester City",
    homeScore: 3,
    awayScore: 2,
    status: "ft",
    date: "2026-03-16",
    homeLogo: "🔴",
    awayLogo: "🔵",
  },
  {
    id: "4",
    tournament: "La Liga",
    homeTeam: "FC Barcelona",
    awayTeam: "Atletico Madrid",
    homeScore: 2,
    awayScore: 0,
    status: "ft",
    date: "2026-03-16",
    homeLogo: "🔵🔴",
    awayLogo: "🔴⚪",
  },
  {
    id: "5",
    tournament: "Serie A",
    homeTeam: "AC Milan",
    awayTeam: "Juventus",
    homeScore: 0,
    awayScore: 0,
    status: "live",
    minute: 23,
    date: "2026-03-17",
    homeLogo: "🔴⚫",
    awayLogo: "⚪⚫",
  },
  {
    id: "6",
    tournament: "Ligue 1",
    homeTeam: "PSG",
    awayTeam: "Marseille",
    homeScore: 0,
    awayScore: 0,
    status: "upcoming",
    date: "2026-03-18",
    homeLogo: "🔵🔴",
    awayLogo: "⚪🔵",
  },
  {
    id: "7",
    tournament: "Botola Pro",
    homeTeam: "Wydad AC",
    awayTeam: "Raja CA",
    homeScore: 1,
    awayScore: 2,
    status: "ft",
    date: "2026-03-15",
    homeLogo: "🔴",
    awayLogo: "🟢",
  },
  {
    id: "8",
    tournament: "Saudi Pro League",
    homeTeam: "Al-Hilal",
    awayTeam: "Al-Ahli",
    homeScore: 3,
    awayScore: 1,
    status: "ft",
    date: "2026-03-15",
    homeLogo: "🔵",
    awayLogo: "🟢",
  },
];

export const news = [
  {
    id: "1",
    title: "Mbappé Scores Hat-Trick in El Clásico Thriller",
    titleFr: "Mbappé inscrit un triplé dans un Clásico palpitant",
    titleAr: "مبابي يسجل هاتريك في كلاسيكو مثير",
    category: "La Liga",
    time: "2h ago",
    featured: true,
  },
  {
    id: "2",
    title: "Champions League Quarter-Final Draw Complete",
    titleFr: "Tirage au sort des quarts de finale de la Ligue des Champions terminé",
    titleAr: "اكتمال قرعة ربع نهائي دوري الأبطال",
    category: "UCL",
    time: "4h ago",
    featured: true,
  },
  {
    id: "3",
    title: "Haaland Breaks Premier League Scoring Record",
    titleFr: "Haaland bat le record de buts en Premier League",
    titleAr: "هالاند يحطم رقم التهديف في الدوري الإنجليزي",
    category: "Premier League",
    time: "6h ago",
    featured: false,
  },
  {
    id: "4",
    title: "Wydad and Raja Deliver Spectacular Derby",
    titleFr: "Le Wydad et le Raja offrent un derby spectaculaire",
    titleAr: "الوداد والرجاء يقدمان ديربي مذهل",
    category: "Botola Pro",
    time: "1d ago",
    featured: false,
  },
];
